select * from global_name;

select * from customers100;

alter table customers rename to customers100;

select * from customer;

select * from Agent;

select * from vehicle;

CREATE TABLE AGENT(AGENT_KEY CHAR(5) PRIMARY KEY,NAME VARCHAR(50) NOT NULL,ADDRESS VARCHAR(70), PHONE NUMBER(10) NOT NULL, PWD VARCHAR(40) NOT NULL);
DESC AGENT;

CREATE TABLE CUSTOMER(CUSTID CHAR(5) PRIMARY KEY,NAME VARCHAR(40),MOBILE NUMBER,ADDRESS VARCHAR(100), AGENT_KEY CHAR(5));
DESC CUSTOMER;

CREATE TABLE VEHICLE(VEH_ID CHAR(6) PRIMARY KEY,CUST_ID CHAR(5),VEH_DESC VARCHAR(50),VEH_NUM VARCHAR(12),VEH_TYPE VARCHAR(20));
DESC VEHICLE;

ALTER TABLE CUSTOMER ADD CONSTRAINT FK_AGENT FOREIGN KEY(AGENT_KEY) REFERENCES AGENT(AGENT_KEY);

ALTER TABLE VEHICLE ADD CONSTRAINT FK_CUSTO FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUSTID);

 ALTER TABLE VEHICLE MODIFY (CUST_ID NOT NULL);
 